CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "FirstName" character varying(25) NOT NULL,
        "LastName" character varying(25) NOT NULL,
        "RefreshToken" text,
        "RefreshTokenExpiresAtUtc" timestamp with time zone,
        "PhoneNumber" character varying(20) NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE TABLE "Address" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BuildingName" character varying(50) NOT NULL,
        "Floor" integer NOT NULL,
        "DoorNo" integer NOT NULL,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_Address" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Address_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('2738d25f-ebd2-4473-816a-5771b5f7c42f', NULL, 'Vendor', 'VENDOR');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('768c88f6-9438-4714-acfe-8f9239836c98', NULL, 'SuperAdmin', 'SUPERADMIN');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('cd56803c-f8ba-4f59-92ff-faee35d567e4', NULL, 'Admin', 'ADMIN');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('d90d48fd-655a-423c-ae20-23fe71107116', NULL, 'Tenants', 'TENANTS');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE UNIQUE INDEX "IX_Address_UserId" ON "Address" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019123952_FirstMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019123952_FirstMigration', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019124110_UpdatedBuildingNameLength') THEN
    ALTER TABLE "Address" ALTER COLUMN "BuildingName" TYPE character varying(30);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251019124110_UpdatedBuildingNameLength') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251019124110_UpdatedBuildingNameLength', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251020112819_UpdatedUserAndAddress') THEN
    ALTER TABLE "Address" ALTER COLUMN "UserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251020112819_UpdatedUserAndAddress') THEN
    UPDATE "AspNetRoles" SET "Name" = 'Tenant', "NormalizedName" = 'TENANT'
    WHERE "Id" = 'd90d48fd-655a-423c-ae20-23fe71107116';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251020112819_UpdatedUserAndAddress') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251020112819_UpdatedUserAndAddress', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021181927_DeletedAddress') THEN
    ALTER TABLE "Address" ALTER COLUMN "BuildingName" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021181927_DeletedAddress') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021181927_DeletedAddress', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021183019_DeletedAddressAttempt2') THEN
    DROP TABLE "Address";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021183019_DeletedAddressAttempt2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021183019_DeletedAddressAttempt2', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021185449_AddBuildingFloorApartment') THEN
    CREATE TABLE "Buildings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        CONSTRAINT "PK_Buildings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021185449_AddBuildingFloorApartment') THEN
    CREATE TABLE "Floors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FloorNumber" integer NOT NULL,
        "BuildingId" integer NOT NULL,
        CONSTRAINT "PK_Floors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Floors_Buildings_BuildingId" FOREIGN KEY ("BuildingId") REFERENCES "Buildings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021185449_AddBuildingFloorApartment') THEN
    CREATE TABLE "Apartments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ApartmentNumber" integer NOT NULL,
        "FloorId" integer NOT NULL,
        CONSTRAINT "PK_Apartments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Apartments_Floors_FloorId" FOREIGN KEY ("FloorId") REFERENCES "Floors" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021185449_AddBuildingFloorApartment') THEN
    CREATE UNIQUE INDEX "IX_Apartments_FloorId_ApartmentNumber" ON "Apartments" ("FloorId", "ApartmentNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021185449_AddBuildingFloorApartment') THEN
    CREATE UNIQUE INDEX "IX_Buildings_Name" ON "Buildings" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021185449_AddBuildingFloorApartment') THEN
    CREATE UNIQUE INDEX "IX_Floors_BuildingId_FloorNumber" ON "Floors" ("BuildingId", "FloorNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251021185449_AddBuildingFloorApartment') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251021185449_AddBuildingFloorApartment', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251022124311_AddedNewAddressEntity') THEN
    CREATE TABLE "Addresses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BuildingId" integer,
        "FloorId" integer,
        "ApartmentId" integer,
        "UserId" uuid,
        CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Addresses_Apartments_ApartmentId" FOREIGN KEY ("ApartmentId") REFERENCES "Apartments" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Addresses_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Addresses_Buildings_BuildingId" FOREIGN KEY ("BuildingId") REFERENCES "Buildings" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Addresses_Floors_FloorId" FOREIGN KEY ("FloorId") REFERENCES "Floors" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251022124311_AddedNewAddressEntity') THEN
    CREATE INDEX "IX_Addresses_ApartmentId" ON "Addresses" ("ApartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251022124311_AddedNewAddressEntity') THEN
    CREATE INDEX "IX_Addresses_BuildingId" ON "Addresses" ("BuildingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251022124311_AddedNewAddressEntity') THEN
    CREATE INDEX "IX_Addresses_BuildingId_FloorId_ApartmentId" ON "Addresses" ("BuildingId", "FloorId", "ApartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251022124311_AddedNewAddressEntity') THEN
    CREATE INDEX "IX_Addresses_FloorId" ON "Addresses" ("FloorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251022124311_AddedNewAddressEntity') THEN
    CREATE UNIQUE INDEX "IX_Addresses_UserId" ON "Addresses" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251022124311_AddedNewAddressEntity') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251022124311_AddedNewAddressEntity', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    DROP INDEX "IX_Addresses_BuildingId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    DROP INDEX "IX_Addresses_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    ALTER INDEX "IX_AspNetUserRoles_RoleId" RENAME TO "IX_UserRoles_RoleId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    ALTER INDEX "RoleNameIndex" RENAME TO "IX_Roles_NormalizedName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_Users_Email" ON "AspNetUsers" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_Users_FirstName" ON "AspNetUsers" ("FirstName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_Users_LastName" ON "AspNetUsers" ("LastName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_Users_PhoneNumber" ON "AspNetUsers" ("PhoneNumber") WHERE "PhoneNumber" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_Users_RefreshToken" ON "AspNetUsers" ("RefreshToken") WHERE "RefreshToken" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_Users_Search_Composite" ON "AspNetUsers" ("Email", "FirstName", "LastName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_UserRoles_UserId" ON "AspNetUserRoles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_Addresses_BuildingId" ON "Addresses" ("BuildingId") WHERE "BuildingId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE UNIQUE INDEX "IX_Addresses_UserId" ON "Addresses" ("UserId") WHERE "UserId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    CREATE INDEX "IX_Addresses_UserId_BuildingId" ON "Addresses" ("UserId", "BuildingId") WHERE "UserId" IS NOT NULL AND "BuildingId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031185047_AddingIndexing') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251031185047_AddingIndexing', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    DROP INDEX "IX_Users_Email";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    DROP INDEX "IX_Users_FirstName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    DROP INDEX "IX_Users_LastName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    DROP INDEX "IX_Users_PhoneNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    CREATE INDEX "IX_Users_Email_Trgm" ON "AspNetUsers" USING gin ("Email" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    CREATE INDEX "IX_Users_FirstName_Trgm" ON "AspNetUsers" USING gin ("FirstName" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    CREATE INDEX "IX_Users_LastName_Trgm" ON "AspNetUsers" USING gin ("LastName" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    CREATE INDEX "IX_Users_PhoneNumber_Trgm" ON "AspNetUsers" USING gin ("PhoneNumber" gin_trgm_ops) WHERE "PhoneNumber" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251031191901_Enable_PgTrgm') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251031191901_Enable_PgTrgm', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102123023_GINTrigramIndexForBuildingName') THEN
    CREATE INDEX "IX_Buildings_Name_Trgm" ON "Buildings" USING gin ("Name" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102123023_GINTrigramIndexForBuildingName') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251102123023_GINTrigramIndexForBuildingName', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102160351_ChangedAptNumberToAptName') THEN
    DROP INDEX "IX_Apartments_FloorId_ApartmentNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102160351_ChangedAptNumberToAptName') THEN
    ALTER TABLE "Apartments" DROP COLUMN "ApartmentNumber";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102160351_ChangedAptNumberToAptName') THEN
    ALTER TABLE "Apartments" ADD "ApartmentName" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102160351_ChangedAptNumberToAptName') THEN
    CREATE UNIQUE INDEX "IX_Apartments_FloorId_ApartmentName" ON "Apartments" ("FloorId", "ApartmentName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251102160351_ChangedAptNumberToAptName') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251102160351_ChangedAptNumberToAptName', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107150515_AddedVendor') THEN
    CREATE TABLE "Vendors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500) NOT NULL,
        "OpeningTime" interval NOT NULL,
        "CloseTime" interval NOT NULL,
        "Type" integer NOT NULL,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Vendors_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107150515_AddedVendor') THEN
    CREATE UNIQUE INDEX "IX_Vendors_Name" ON "Vendors" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107150515_AddedVendor') THEN
    CREATE INDEX "IX_Vendors_Name_Trgm" ON "Vendors" USING gin ("Name" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107150515_AddedVendor') THEN
    CREATE INDEX "IX_Vendors_Type" ON "Vendors" ("Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107150515_AddedVendor') THEN
    CREATE UNIQUE INDEX "IX_Vendors_UserId" ON "Vendors" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107150515_AddedVendor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251107150515_AddedVendor', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107182206_AddedUserProfile') THEN
    ALTER TABLE "AspNetUsers" ADD "ProfileImageUrl" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251107182206_AddedUserProfile') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251107182206_AddedUserProfile', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251115212952_AddImageUrlToVendor') THEN
    ALTER TABLE "Vendors" ADD "ProfileImageUrl" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251115212952_AddImageUrlToVendor') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251115212952_AddImageUrlToVendor', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "ParentCategoryId" integer,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VendorId" integer NOT NULL,
        "CategoryId" integer,
        "Name" character varying(30) NOT NULL,
        "Description" character varying(2000) NOT NULL,
        "Price" numeric(10,2) NOT NULL,
        "DiscountPrice" numeric(10,2),
        "InStock" boolean NOT NULL,
        "ProductImageUrl" text NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Products_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE UNIQUE INDEX "IX_Categories_Name" ON "Categories" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE INDEX "IX_Categories_Name_Trgm" ON "Categories" USING gin ("Name" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE INDEX "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE INDEX "IX_Products_InStock" ON "Products" ("InStock");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE INDEX "IX_Products_Name" ON "Products" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE INDEX "IX_Products_Name_Trgm" ON "Products" USING gin ("Name" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE INDEX "IX_Products_VendorId" ON "Products" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    CREATE INDEX "IX_Products_VendorId_InStock" ON "Products" ("VendorId", "InStock");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251123172355_AddedProductAndCatagory') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251123172355_AddedProductAndCatagory', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderNumber" character varying(50) NOT NULL,
        "UserId" uuid NOT NULL,
        "VendorId" integer NOT NULL,
        "AddressId" integer,
        "Subtotal" numeric(10,2) NOT NULL,
        "DeliveryFee" numeric(10,2) NOT NULL,
        "TotalAmount" numeric(10,2) NOT NULL,
        "Status" integer NOT NULL,
        "Notes" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE TABLE "OrderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(10,2) NOT NULL,
        "TotalPrice" numeric(10,2) NOT NULL,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    UPDATE "AspNetRoles" SET "ConcurrencyStamp" = '8554d40c-ee93-4b5e-b3a1-e072b71877c7'
    WHERE "Id" = '2738d25f-ebd2-4473-816a-5771b5f7c42f';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    UPDATE "AspNetRoles" SET "ConcurrencyStamp" = 'c1672889-7933-4585-8684-9a899fc55687'
    WHERE "Id" = '768c88f6-9438-4714-acfe-8f9239836c98';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    UPDATE "AspNetRoles" SET "ConcurrencyStamp" = '368749f9-79cd-46c6-bbc1-72fe6d3365d5'
    WHERE "Id" = 'cd56803c-f8ba-4f59-92ff-faee35d567e4';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    UPDATE "AspNetRoles" SET "ConcurrencyStamp" = '6dc9dea8-7375-4a4d-b35b-8b18670eb407'
    WHERE "Id" = 'd90d48fd-655a-423c-ae20-23fe71107116';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE INDEX "IX_OrderItems_ProductId" ON "OrderItems" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE INDEX "IX_Orders_AddressId" ON "Orders" ("AddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE INDEX "IX_Orders_CreatedAt" ON "Orders" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE UNIQUE INDEX "IX_Orders_OrderNumber" ON "Orders" ("OrderNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE INDEX "IX_Orders_Status" ON "Orders" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    CREATE INDEX "IX_Orders_VendorId" ON "Orders" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129151036_AddOrderEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251129151036_AddOrderEntities', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130124314_AddedNotification') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Message" character varying(1000) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "IsRead" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ActionUrl" character varying(500),
        "Metadata" jsonb,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130124314_AddedNotification') THEN
    CREATE INDEX "IX_Notifications_CreatedAt" ON "Notifications" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130124314_AddedNotification') THEN
    CREATE INDEX "IX_Notifications_IsRead" ON "Notifications" ("IsRead");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130124314_AddedNotification') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130124314_AddedNotification') THEN
    CREATE INDEX "IX_Notifications_UserId_IsRead" ON "Notifications" ("UserId", "IsRead");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130124314_AddedNotification') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251130124314_AddedNotification', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201133614_AddedIsWeightableToProducts') THEN
    ALTER TABLE "Products" ADD "IsWeightable" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251201133614_AddedIsWeightableToProducts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251201133614_AddedIsWeightableToProducts', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251204224231_AddVendorStaff') THEN
    CREATE TABLE "VendorStaff" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "VendorId" integer NOT NULL,
        "AssignedDate" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_VendorStaff" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VendorStaff_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VendorStaff_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251204224231_AddVendorStaff') THEN
    CREATE INDEX "IX_VendorStaff_IsActive" ON "VendorStaff" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251204224231_AddVendorStaff') THEN
    CREATE INDEX "IX_VendorStaff_UserId" ON "VendorStaff" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251204224231_AddVendorStaff') THEN
    CREATE UNIQUE INDEX "IX_VendorStaff_UserId_VendorId" ON "VendorStaff" ("UserId", "VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251204224231_AddVendorStaff') THEN
    CREATE INDEX "IX_VendorStaff_VendorId" ON "VendorStaff" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251204224231_AddVendorStaff') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251204224231_AddVendorStaff', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209160027_AddAuditLogs') THEN
    CREATE TABLE "AuditLogs" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid,
        "UserEmail" character varying(256),
        "EntityName" character varying(128) NOT NULL,
        "EntityId" character varying(128) NOT NULL,
        "Action" character varying(20) NOT NULL,
        "OldValues" jsonb,
        "NewValues" jsonb,
        "AffectedColumns" jsonb,
        "Timestamp" timestamp with time zone NOT NULL,
        "IpAddress" character varying(45),
        "UserAgent" character varying(512),
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditLogs_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209160027_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_Action" ON "AuditLogs" ("Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209160027_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_Entity" ON "AuditLogs" ("EntityName", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209160027_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_EntityName" ON "AuditLogs" ("EntityName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209160027_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209160027_AddAuditLogs') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209160027_AddAuditLogs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251209160027_AddAuditLogs', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209171621_RemoveIpAddressFromAuditLog') THEN
    ALTER TABLE "AuditLogs" DROP COLUMN "IpAddress";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251209171621_RemoveIpAddressFromAuditLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251209171621_RemoveIpAddressFromAuditLog', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211141548_AddVendorStaffAndDriverRoles') THEN
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('a1b2c3d4-e5f6-7890-abcd-ef1234567890', 'f1a2b3c4-d5e6-7890-abcd-ef1234567890', 'VendorStaff', 'VENDORSTAFF');
    INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
    VALUES ('b2c3d4e5-f6a7-8901-bcde-f12345678901', 'a2b3c4d5-e6f7-8901-bcde-f23456789012', 'VendorDriver', 'VENDORDRIVER');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211141548_AddVendorStaffAndDriverRoles') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251211141548_AddVendorStaffAndDriverRoles', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227181400_AddedEntityImage') THEN
    CREATE TABLE "EntityImages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EntityType" character varying(50) NOT NULL,
        "EntityId" character varying(128) NOT NULL,
        "ImageUrl" character varying(500) NOT NULL,
        "DisplayOrder" integer NOT NULL,
        "IsPrimary" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_EntityImages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227181400_AddedEntityImage') THEN
    CREATE INDEX "IX_EntityImages_EntityType_EntityId" ON "EntityImages" ("EntityType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227181400_AddedEntityImage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251227181400_AddedEntityImage', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227182758_AddedSupportTicket') THEN
    CREATE TABLE "SupportTickets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TicketNumber" character varying(50) NOT NULL,
        "UserId" uuid NOT NULL,
        "Subject" character varying(200) NOT NULL,
        "Description" character varying(2000) NOT NULL,
        "Status" integer NOT NULL,
        "Priority" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ResolvedAt" timestamp with time zone,
        "AdminNotes" character varying(1000),
        CONSTRAINT "PK_SupportTickets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SupportTickets_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227182758_AddedSupportTicket') THEN
    CREATE INDEX "IX_SupportTickets_CreatedAt" ON "SupportTickets" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227182758_AddedSupportTicket') THEN
    CREATE INDEX "IX_SupportTickets_Status" ON "SupportTickets" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227182758_AddedSupportTicket') THEN
    CREATE UNIQUE INDEX "IX_SupportTickets_TicketNumber" ON "SupportTickets" ("TicketNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227182758_AddedSupportTicket') THEN
    CREATE INDEX "IX_SupportTickets_UserId" ON "SupportTickets" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251227182758_AddedSupportTicket') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251227182758_AddedSupportTicket', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251231022048_AddApartmentLayout') THEN
    ALTER TABLE "Apartments" ADD "Layout" jsonb;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251231022048_AddApartmentLayout') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251231022048_AddApartmentLayout', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE TABLE "DriverShifts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "DriverId" uuid NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "EndedAt" timestamp with time zone,
        CONSTRAINT "PK_DriverShifts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DriverShifts_AspNetUsers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE TABLE "OrderAssignments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "DriverId" uuid NOT NULL,
        "ShiftId" integer,
        "OfferedAt" timestamp with time zone NOT NULL,
        "RespondedAt" timestamp with time zone,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_OrderAssignments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderAssignments_AspNetUsers_DriverId" FOREIGN KEY ("DriverId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderAssignments_DriverShifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "DriverShifts" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_OrderAssignments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    UPDATE "AspNetRoles" SET "Name" = 'Driver', "NormalizedName" = 'DRIVER'
    WHERE "Id" = 'b2c3d4e5-f6a7-8901-bcde-f12345678901';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE INDEX "IX_DriverShifts_DriverId" ON "DriverShifts" ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE INDEX "IX_DriverShifts_DriverId_EndedAt" ON "DriverShifts" ("DriverId", "EndedAt") WHERE "EndedAt" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE INDEX "IX_OrderAssignments_DriverId" ON "OrderAssignments" ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE INDEX "IX_OrderAssignments_OrderId" ON "OrderAssignments" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE INDEX "IX_OrderAssignments_OrderId_Status" ON "OrderAssignments" ("OrderId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE INDEX "IX_OrderAssignments_ShiftId" ON "OrderAssignments" ("ShiftId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    CREATE INDEX "IX_OrderAssignments_Status_ExpiresAt" ON "OrderAssignments" ("Status", "ExpiresAt") WHERE "Status" = 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260108223621_AddDriverDispatchEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260108223621_AddDriverDispatchEntities', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" DROP CONSTRAINT "FK_Addresses_Apartments_ApartmentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" DROP CONSTRAINT "FK_Addresses_AspNetUsers_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" DROP CONSTRAINT "FK_Addresses_Buildings_BuildingId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" DROP CONSTRAINT "FK_Addresses_Floors_FloorId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP TABLE "Apartments";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP TABLE "Floors";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP TABLE "Buildings";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP INDEX "IX_Addresses_ApartmentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP INDEX "IX_Addresses_BuildingId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP INDEX "IX_Addresses_BuildingId_FloorId_ApartmentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP INDEX "IX_Addresses_FloorId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP INDEX "IX_Addresses_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    DROP INDEX "IX_Addresses_UserId_BuildingId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" DROP COLUMN "ApartmentId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" DROP COLUMN "BuildingId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" DROP COLUMN "FloorId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    UPDATE "Addresses" SET "UserId" = '00000000-0000-0000-0000-000000000000' WHERE "UserId" IS NULL;
    ALTER TABLE "Addresses" ALTER COLUMN "UserId" SET NOT NULL;
    ALTER TABLE "Addresses" ALTER COLUMN "UserId" SET DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "AdditionalDirections" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "ApartmentNumber" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "BuildingName" character varying(255);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "CompanyName" character varying(255);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "CreatedBy" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "Floor" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "HouseName" character varying(255);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "HouseNumber" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "IsDefault" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "Label" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "LastModifiedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "LastModifiedBy" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "Latitude" double precision NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "Longitude" double precision NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "PhoneNumber" character varying(30) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "Street" character varying(255) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD "Type" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    UPDATE "AspNetRoles" SET "Name" = 'Customer', "NormalizedName" = 'CUSTOMER'
    WHERE "Id" = 'd90d48fd-655a-423c-ae20-23fe71107116';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    CREATE UNIQUE INDEX "IX_Addresses_UserId_IsDefault" ON "Addresses" ("UserId") WHERE "IsDefault" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    ALTER TABLE "Addresses" ADD CONSTRAINT "FK_Addresses_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419003949_ReplaceAddressSystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419003949_ReplaceAddressSystem', '9.0.10');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    ALTER TABLE "Categories" DROP CONSTRAINT "FK_Categories_Categories_ParentCategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    DROP INDEX "IX_Categories_Name_Trgm";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    DROP INDEX "IX_Categories_ParentCategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    ALTER TABLE "Vendors" RENAME COLUMN "Type" TO "VendorCategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    ALTER INDEX "IX_Vendors_Type" RENAME TO "IX_Vendors_VendorCategoryId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    ALTER TABLE "Categories" RENAME COLUMN "ParentCategoryId" TO "SortOrder";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    ALTER TABLE "Categories" ADD "VendorId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    CREATE TABLE "VendorCategories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(500),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VendorCategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    CREATE INDEX "IX_Categories_Name_Trgm" ON "Categories" USING gin ("Name" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    CREATE INDEX "IX_Categories_VendorId" ON "Categories" ("VendorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    CREATE UNIQUE INDEX "IX_Categories_VendorId_Name" ON "Categories" ("VendorId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    CREATE INDEX "IX_VendorCategories_IsActive" ON "VendorCategories" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    CREATE UNIQUE INDEX "IX_VendorCategories_Name_Trgm" ON "VendorCategories" USING gin ("Name" gin_trgm_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    ALTER TABLE "Categories" ADD CONSTRAINT "FK_Categories_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    ALTER TABLE "Vendors" ADD CONSTRAINT "FK_Vendors_VendorCategories_VendorCategoryId" FOREIGN KEY ("VendorCategoryId") REFERENCES "VendorCategories" ("Id") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260420011548_ReplaceCategorySystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260420011548_ReplaceCategorySystem', '9.0.10');
    END IF;
END $EF$;
COMMIT;

