START TRANSACTION;
ALTER TABLE "Notifications" ADD "ImageUrl" character varying(1000);

CREATE TABLE "DeviceTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "Token" character varying(500) NOT NULL,
    "Platform" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastSeenAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DeviceTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DeviceTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_DeviceTokens_Token" ON "DeviceTokens" ("Token");

CREATE INDEX "IX_DeviceTokens_UserId" ON "DeviceTokens" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260424160417_AddPushNotificationInfra', '9.0.10');

COMMIT;

